controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /api

homepage:
    path: /
    controller: App\Controller\DefaultController::index
    defaults:
        route: homepage
        permanent: true

logout:
    path: /api/logout
    methods: [GET]
    defaults:
        _controller: |
            function () {
            }
